CREATE TABLE PRODUTOS (
	ID varchar(36) NOT NULL,
	DESCRICAO varchar(50) NOT NULL,
	UNIDADE varchar(5) NULL,
	PRECO decimal(13,2) DEFAULT 0 NOT NULL,
	ATIVO bit DEFAULT 1 NOT NULL,
	USUARIOINCLUSAO varchar(50) NOT NULL,
	DATAINCLUSAO datetime DEFAULT getdate() NOT NULL,
	CONSTRAINT PK_PRODUTOS PRIMARY KEY (ID)
);
